### ISSUE TITLE
theoretical kurtosis

### ISSUE THREAD

**Issue by stephenhky** [gmgeorg/LambertW#2]
In functions such as `IGMM` and `delta_GMM`, there is a default input parameter called `theoretical.kurtosis`, which is usually set to 3. Is there a particular reason why? If I have to provide a theoretical kurtosis, what is the best way to determine the theoretical kurtosis value (not the empirical one)?

**Comment by stephenhky** [comment]
Never. I got it.

**Comment by gmgeorg** [comment]
Following up for future reference:

The `theoretical.kurtosis` gets chosen by the user as a way to characterize the input distribution properties they want to obtain when using the method of moments estimators.  It defaults to `3` since thats the theoretical (population) kurotis of a Normal distribution, which is the default for the h and hh type Lambert W x F distributions (in location / scale case).
In case you are working with scale family distribution and the observed data looks like a heavy tailed version of an exponential distribution then it may make sense to use `theoretical.kurtosis = 9` to obtain a methods of moments estimate for a Lambert W x exponential distribution (since kurotis of an exponential is 9 -- see [wiki](https://en.wikipedia.org/wiki/Exponential_distribution)).
